### ISSUE TITLE
FAQ - add compappend 

### ISSUE THREAD

**Issue by ShalokShalom** [elm-community/elm-community.github.io#1]
Wherever you contain the actual data for this webpage; 

This here is outdated, since there is now a forth supertype: 

http://faq.elm-community.org/#does-elm-have-ad-hoc-polymorphism-or-typeclasses

**Comment by fredcy** [comment]
Do you mean `compappend`? If so, see the footnote. If not, what is that fourth supertype and where can I find info about it?

**Comment by ShalokShalom** [comment]
Compappend yeah. The footnote where? Why not place an info where it's relevant?

**Comment by ShalokShalom** [comment]
oO Is this resolved by now?
